export enum TokenType {
  // Structural tokens
  L_PAREN = 'L_PAREN',
  R_PAREN = 'R_PAREN',
  L_BRACKET = 'L_BRACKET',
  R_BRACKET = 'R_BRACKET',
  L_BRACE = 'L_BRACE',
  R_BRACE = 'R_BRACE',
  COMMA = 'COMMA',
  DOT = 'DOT',
  SEMICOLON = 'SEMICOLON',
  COLON = 'COLON',

  // Operators
  DASH = 'DASH',
  PLUS = 'PLUS',
  STAR = 'STAR',
  SLASH = 'SLASH',
  BACKSLASH = 'BACKSLASH',
  PIPE = 'PIPE',
  DPIPE = 'DPIPE',
  AMP = 'AMP',
  DAMP = 'DAMP',
  CARET = 'CARET',
  TILDA = 'TILDA',
  PERCENT = 'PERCENT',

  // Comparison operators
  LT = 'LT',
  LTE = 'LTE',
  GT = 'GT',
  GTE = 'GTE',
  EQ = 'EQ',
  NEQ = 'NEQ',
  NULLSAFE_EQ = 'NULLSAFE_EQ',

  // Logical operators
  AND = 'AND',
  OR = 'OR',
  NOT = 'NOT',
  XOR = 'XOR',

  // Special operators
  ARROW = 'ARROW',
  DARROW = 'DARROW',
  HASH = 'HASH',
  DCOLON = 'DCOLON',
  PARAMETER = 'PARAMETER',

  // Literals and identifiers
  NUMBER = 'NUMBER',
  STRING = 'STRING',
  IDENTIFIER = 'IDENTIFIER',
  COLUMN = 'COLUMN',

  // Keywords (SQL reserved words)
  SELECT = 'SELECT',
  FROM = 'FROM',
  WHERE = 'WHERE',
  AS = 'AS',
  JOIN = 'JOIN',
  LEFT = 'LEFT',
  RIGHT = 'RIGHT',
  INNER = 'INNER',
  OUTER = 'OUTER',
  ON = 'ON',
  USING = 'USING',
  GROUP = 'GROUP',
  BY = 'BY',
  HAVING = 'HAVING',
  ORDER = 'ORDER',
  ASC = 'ASC',
  DESC = 'DESC',
  LIMIT = 'LIMIT',
  OFFSET = 'OFFSET',
  UNION = 'UNION',
  INTERSECT = 'INTERSECT',
  EXCEPT = 'EXCEPT',
  ALL = 'ALL',
  DISTINCT = 'DISTINCT',
  CASE = 'CASE',
  WHEN = 'WHEN',
  THEN = 'THEN',
  ELSE = 'ELSE',
  END = 'END',
  CAST = 'CAST',
  NULL = 'NULL',
  IS = 'IS',
  IN = 'IN',
  BETWEEN = 'BETWEEN',
  LIKE = 'LIKE',
  EXISTS = 'EXISTS',
  CREATE = 'CREATE',
  TABLE = 'TABLE',
  VIEW = 'VIEW',
  INSERT = 'INSERT',
  INTO = 'INTO',
  VALUES = 'VALUES',
  UPDATE = 'UPDATE',
  SET = 'SET',
  DELETE = 'DELETE',
  DROP = 'DROP',
  ALTER = 'ALTER',
  ADD = 'ADD',
  COLUMN_KW = 'COLUMN_KW',
  PRIMARY = 'PRIMARY',
  KEY = 'KEY',
  FOREIGN = 'FOREIGN',
  REFERENCES = 'REFERENCES',
  INDEX = 'INDEX',
  UNIQUE = 'UNIQUE',
  DEFAULT = 'DEFAULT',
  CHECK = 'CHECK',
  CONSTRAINT = 'CONSTRAINT',

  // Data types
  INT = 'INT',
  INTEGER = 'INTEGER',
  BIGINT = 'BIGINT',
  SMALLINT = 'SMALLINT',
  TINYINT = 'TINYINT',
  FLOAT = 'FLOAT',
  DOUBLE = 'DOUBLE',
  DECIMAL = 'DECIMAL',
  NUMERIC = 'NUMERIC',
  BOOLEAN = 'BOOLEAN',
  BOOL = 'BOOL',
  DATE = 'DATE',
  DATETIME = 'DATETIME',
  TIMESTAMP = 'TIMESTAMP',
  TIME = 'TIME',
  VARCHAR = 'VARCHAR',
  CHAR = 'CHAR',
  TEXT = 'TEXT',

  // Special tokens
  SPACE = 'SPACE',
  BREAK = 'BREAK',
  COMMENT = 'COMMENT',
  HINT = 'HINT',
  VAR = 'VAR',
  EOF = 'EOF',
}

export class Token {
  constructor(
    public readonly type: TokenType,
    public readonly text: string,
    public readonly line: number = 1,
    public readonly col: number = 1,
    public readonly start: number = 0,
    public readonly end: number = 0,
    public readonly comments: string[] = []
  ) {}

  toString(): string {
    return `Token(${this.type}, '${this.text}', ${this.line}:${this.col})`;
  }
}
