on: [pull_request]
name: benchmark pull requests
jobs:
  run-benchmark:
    name: run benchmark
    runs-on: ubuntu-latest
    if: ${{ false }}  # Uncomment this when the workflow is fixed (currently fails in PRs)
    steps:
      - uses: actions/checkout@v4
      - uses: boa-dev/criterion-compare-action@v3
        with:
          branchName: ${{ github.base_ref }}
          cwd: "sqlglotrs"
